services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${SHORTENER_DB}
      POSTGRES_USER: ${SHORTENER_DB_USERNAME}
      POSTGRES_PASSWORD: ${SHORTENER_DB_PASSWORD}

    volumes:
      - shortener-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SHORTENER_DB_USERNAME} -d ${SHORTENER_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7


  shortener-service:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${SHORTENER_DB}
      DB_USERNAME: ${SHORTENER_DB_USERNAME}
      DB_PASSWORD: ${SHORTENER_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ANALYTICS_BASE_URL: http://analytics-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  analytics-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${ANALYTICS_DB}
      POSTGRES_USER: ${ANALYTICS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD}

    volumes:
      - analytics-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ANALYTICS_DB_USERNAME} -d ${ANALYTICS_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  analytics-service:
    build:
      context: ./analytics-service

    environment:
      DB_URL: jdbc:postgresql://analytics-postgres:5432/${ANALYTICS_DB}
      DB_USERNAME: ${ANALYTICS_DB_USERNAME}
      DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      analytics-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - shortener-service
      - analytics-service
  grafana:
    image: grafana/grafana:13.2.1
    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "127.0.0.1:3000:3000"


volumes:
  shortener-postgres-data:
  analytics-postgres-data:
  grafana-data: