services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - shortener-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 5
  shortener-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/shortener
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  shortener-postgres-data: