spring:
  application:
    name: shortener-service
  cache:
    type: redis

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/shortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080


