apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config

data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ANALYTICS_BASE_URL: http://analytics-service:8081
  SHORTENER_DB_URL: jdbc:postgresql://postgres:5432/shortener
  ANALYTICS_DB_URL: jdbc:postgresql://analytics-postgres:5432/analytics_db