apiVersion: apps/v1
kind: Deployment

metadata:
  name: shortener-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shortener-service

  template:
    metadata:
      labels:
        app: shortener-service

    spec:
      containers:
        - name: shortener-service
          image: shortener-service-shortener-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SHORTENER_DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT

            - name: ANALYTICS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ANALYTICS_BASE_URL